services:
  # Backend API service
  - type: web
    name: backend
    runtime: python3.9
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: |
      mkdir -p /opt/render/project/src/data
      cd backend && gunicorn --bind 0.0.0.0:$PORT --workers 1 --worker-class uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: USE_STEALTH_MODE
        value: true

  # Frontend web service
  - type: web
    name: frontend
    env: node
    buildCommand: |
      export VITE_API_BASE_URL=https://basic-youtube-voice-cloning-app.onrender.com
      cd frontend
      npm install && npm run build
    startCommand: cd frontend && npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: VITE_API_BASE_URL
        value: https://basic-youtube-voice-cloning-app.onrender.com 