services:
  # Backend API service
  - type: web
    name: backend
    runtime: python3.9
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT --workers 1 --worker-class uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: USE_STEALTH_MODE
        value: true

  # Frontend web service
  - type: web
    name: frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          name: backend
          type: web
          property: url 